### ISSUE TITLE
macos 使用typora执行脚本报错

### ISSUE THREAD

**Issue by zorohu** [JeroGC/Typora-OneIndex-upload-script#1]
python3 /Users/author/bin/PicUploader.py "/Applications/Typora.app/Contents/Resources/TypeMark/assets/icon/icon_512x512.png"

错误：Traceback (most recent call last): File "/Users/author/bin/PicUploader.py", line 2, in <module> import os, random, sys, requests ModuleNotFoundError: No module named 'requests' Traceback (most recent call last): File "/Users/author/bin/PicUploader.py", line 2, in <module> import os, random, sys, requests ModuleNotFoundError: No module named 'requests'

描述：使用命令行可以成功上传，但是用同样的命令在typora上执行，就会出现模块找不到

**Comment by zorohu** [comment]
这应该是typora对python的支持问题，我使用golang实现了一下可以了
